import Image from "next/image";
import Link from "next/link";
import { ArrowDown, MapPin, Sparkles } from "lucide-react";
import { WhatsAppButton } from "@/src/components/WhatsApp";
import { Faq, FinalCta, Location, PortfolioPreview, Reviews, Services } from "@/src/components/Sections";
import { getGooglePlace } from "@/src/lib/google-places";

export default async function Home() {
  const place = await getGooglePlace();
  return <><section className="hero"><Image src="/images/studio/hero-editorial.png" alt="Imagem editorial de um ambiente de beleza elegante" fill priority sizes="100vw"/><div className="hero-shade"/><div className="hero-content"><span className="eyebrow">Studio DM · Vitória Moraes</span><h1>Realce sua beleza.<br/><em>Valorize o seu olhar.</em></h1><p>Atendimento personalizado em sobrancelhas e cílios, com cuidado, leveza e atenção ao que faz você se sentir única.</p><div className="actions"><WhatsAppButton event="click_whatsapp_hero" label="Agendar meu horário"/><Link className="button ghost" href="/portfolio">Conhecer os trabalhos</Link></div><span className="place"><MapPin size={16}/> Itapecerica da Serra, SP</span></div><a className="scroll" href="#destaques" aria-label="Ver mais"><ArrowDown/></a></section><div className="trust" id="destaques"><span><Sparkles/>Atendimento personalizado</span><span>Beleza com naturalidade</span><span>Em Itapecerica da Serra</span></div><Services/><PortfolioPreview/><section className="about-home"><div className="portrait"><Image src="/images/vitoria/vitoria-moraes-retrato.png" alt="Vitória Moraes, profissional à frente do Studio DM" fill sizes="(max-width: 800px) 100vw, 45vw"/></div><div><span>Vitória Moraes</span><h2>Beleza nasce quando você se reconhece.</h2><p>À frente do Studio DM, Vitória conduz cada atendimento de forma próxima e individual. O cuidado começa na conversa e segue em escolhas que respeitam seus traços e preferências.</p><Link className="text-link" href="/sobre">Conheça a profissional →</Link></div></section><Reviews place={place}/><section><div className="experience"><div><span>01</span><h3>Escuta</h3><p>O atendimento começa entendendo suas preferências e sua rotina.</p></div><div><span>02</span><h3>Cuidado</h3><p>Cada etapa é conduzida com atenção, higiene e orientação.</p></div><div><span>03</span><h3>Naturalidade</h3><p>O objetivo é valorizar sua expressão sem apagar sua identidade.</p></div></div></section><Faq/><Location/><FinalCta/></>;
}
