import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, MapPin, Star } from "lucide-react";
import { services } from "@/src/data/services";
import { portfolio } from "@/src/data/portfolio";
import { faq } from "@/src/data/faq";
import { business, isPending } from "@/src/config/business";
import { WhatsAppButton } from "./WhatsApp";
import type { GooglePlace } from "@/src/lib/google-places";

export function SectionHeading({kicker,title,intro}:{kicker:string;title:string;intro?:string}){return <div className="section-heading"><span>{kicker}</span><h2>{title}</h2>{intro&&<p>{intro}</p>}</div>}
export function Services(){return <section><SectionHeading kicker="Serviços" title="Cuidado pensado para o seu olhar" intro="Cada atendimento começa pela escuta: o resultado deve combinar com seus traços, sua rotina e o que faz você se sentir bem."/><div className="service-grid">{services.map((s,i)=><article className="service-card" key={s.slug}><small>0{i+1} · {s.eyebrow}</small><h3>{s.name}</h3><p>{s.description}</p><ul>{s.benefits.map(b=><li key={b}><Check size={15}/>{b}</li>)}</ul><Link href={`/servicos/${s.slug}`}>Conhecer o serviço <ArrowRight size={16}/></Link></article>)}</div></section>}
export function PortfolioPreview(){return <section className="band"><SectionHeading kicker="Portfólio" title="Detalhes que transformam o olhar" intro="Conheça de perto a delicadeza, a técnica e o cuidado presentes em cada resultado."/><div className="portfolio-grid">{portfolio.filter(x=>x.usageAuthorized).map(item=><figure className="portfolio-item" key={item.id}><Image src={item.image} alt={item.alt} width={item.width} height={item.height} sizes="(max-width: 800px) 100vw, 1192px"/><figcaption><b>{item.title}</b><span>{item.description}</span></figcaption></figure>)}</div><Link className="text-link" href="/portfolio">Ver o portfólio <ArrowRight size={16}/></Link></section>}
export function Reviews({place}:{place:GooglePlace|null}){const rating=place?.rating??business.googleRating;const count=place?.userRatingCount??business.googleReviewCount;return <section><SectionHeading kicker="Avaliações no Google" title="A experiência de quem já conhece"/><div className="rating"><Star fill="currentColor"/> <strong>{rating.toFixed(1).replace(".",",")}</strong><span>{count} avaliações no Google</span></div>{place?.reviews?.length?<div className="review-grid">{place.reviews.slice(0,3).map(r=><article className="review" key={r.name}><div className="stars">{"★".repeat(r.rating)}</div><p>“{r.text?.text}”</p><a href={r.authorAttribution.uri} target="_blank">{r.authorAttribution.displayName}</a><small>{r.relativePublishTimeDescription} · Google</small></article>)}</div>:null}<a className="button outline" href={place?.googleMapsUri||business.googleReviewUrl} target="_blank">Ver avaliações no Google</a></section>}
export function Faq(){return <section className="band"><SectionHeading kicker="Dúvidas frequentes" title="Antes do seu atendimento"/><div className="faq">{faq.map(x=><details key={x.q}><summary>{x.q}<span>+</span></summary><p>{x.a}</p></details>)}</div></section>}
export function Location(){const confirmed=!isPending(business.address);const embed=`https://www.google.com/maps?q=${business.latitude},${business.longitude}&z=17&output=embed`;return <section><div className="location"><div><SectionHeading kicker="Localização" title="Studio DM em Itapecerica da Serra"/><p><MapPin size={18}/> {confirmed?business.address:"Endereço completo em confirmação"}</p><p>{business.city} - {business.state}, {business.postalCode}</p><div className="actions"><a className="button outline" href={business.googleMapsUrl} target="_blank">Abrir rota</a><WhatsAppButton/></div></div><iframe className="map-frame" src={embed} title="Mapa do Studio DM em Itapecerica da Serra" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/></div></section>}
export function FinalCta(){return <section className="cta"><span>Studio DM · Vitória Moraes</span><h2>Seu próximo momento de autocuidado começa aqui.</h2><WhatsAppButton label="Agendar agora"/></section>}
